/**
 * The checklist library for manual social media audits. Nothing here is generated by AI:
 * these are the checkpoints an auditor works through and marks as they review the accounts.
 */

export const PLATFORMS = [
  { key: "instagram", label: "Instagram" },
  { key: "facebook", label: "Facebook" },
  { key: "linkedin", label: "LinkedIn" },
  { key: "youtube", label: "YouTube" },
  { key: "x", label: "X (Twitter)" },
  { key: "tiktok", label: "TikTok" },
  { key: "pinterest", label: "Pinterest" },
] as const;
export type PlatformKey = (typeof PLATFORMS)[number]["key"];
export const platformLabel = (k: string) => PLATFORMS.find((p) => p.key === k)?.label ?? k;

export type LibrarySection = { key: string; title: string; description: string; group: "general" | "platform"; platform?: PlatformKey; items: string[] };

export const LIBRARY: LibrarySection[] = [
  // ---- General sections
  { key: "profile-branding", group: "general", title: "Profiles and branding", description: "Are the accounts complete, consistent and easy to recognise?", items: [
    "Handle and display name match the brand on every platform",
    "Profile picture is the current logo and stays legible when small",
    "Bio says what the business does, for whom, and where",
    "Bio includes a clear call to action",
    "Link in bio goes to a relevant, working page",
    "Contact options are switched on (email, call, directions, WhatsApp)",
    "Cover images and banners are current and on brand",
    "Business category and location are set correctly",
    "Accounts are verified or claimed where that option exists",
  ] },
  { key: "content-strategy", group: "general", title: "Content strategy", description: "Is there a plan behind what gets posted and when?", items: [
    "Content pillars are defined and visible in the feed",
    "Posting frequency is consistent week to week",
    "Mix of formats is used (video, carousels, images, text, stories)",
    "A content calendar exists and is followed",
    "Posts speak to a defined audience and its questions",
    "Captions are useful, on brand and include a call to action",
    "Hashtags and keywords are relevant, not stuffed",
    "Seasonal, event and trend content is used where it fits",
    "User generated content and testimonials are shared",
    "Old high performing posts are reused or refreshed",
  ] },
  { key: "creative-quality", group: "general", title: "Creative and visual quality", description: "Does the content look and sound professional and on brand?", items: [
    "Visual style is consistent (colors, fonts, templates)",
    "Images are sharp and correctly sized for each platform",
    "Video hooks the viewer in the first three seconds",
    "Videos have captions or subtitles",
    "Cover images and thumbnails are designed, not random frames",
    "Carousels are easy to read and end with a call to action",
    "Tone of voice is consistent and human",
    "No spelling mistakes or broken formatting in recent posts",
  ] },
  { key: "engagement-community", group: "general", title: "Engagement and community", description: "How well does the brand talk with its audience?", items: [
    "Comments are answered promptly",
    "Direct messages are answered within a day",
    "Replies are helpful and on tone, including for complaints",
    "Engagement rate is healthy for the account size",
    "Posts ask questions or start conversations",
    "The brand engages with other accounts, not just its own",
    "Community guidelines and spam handling are in place",
    "Reviews and recommendations are monitored and answered",
  ] },
  { key: "growth-reach", group: "general", title: "Growth and reach", description: "Is the audience growing, and is it the right audience?", items: [
    "Follower growth is steady over the last 90 days",
    "Reach and impressions are trending up",
    "Followers match the target customer (location, interests)",
    "Collaborations, partnerships or influencers are used",
    "Other accounts and locations are tagged where relevant",
    "Employees and customers help amplify content",
    "Accounts are cross-promoted across platforms and the website",
  ] },
  { key: "conversion-funnel", group: "general", title: "Conversion and funnel", description: "Does social activity lead to enquiries and sales?", items: [
    "Every profile has one clear next step for the visitor",
    "Links use tracking parameters (UTM) so results can be measured",
    "Landing pages match the promise made in the post",
    "Lead capture is in place (forms, DMs, WhatsApp, booking links)",
    "Shop, catalog or product tags are set up where relevant",
    "Tracking pixels or conversion APIs are installed",
    "Offers and promotions are visible and time-bound",
    "Leads from social are recorded and followed up",
  ] },
  { key: "paid-social", group: "general", title: "Paid social", description: "Only if the brand runs or has run ads.", items: [
    "Ad accounts are set up correctly with billing and access controls",
    "Campaign objectives match business goals",
    "Audiences are defined and tested (custom, lookalike, interest)",
    "Ad creative is refreshed regularly",
    "Copy and creative are tested against variants",
    "Retargeting is in place for site visitors and engagers",
    "Cost per result is tracked against a target",
  ] },
  { key: "analytics-reporting", group: "general", title: "Analytics and reporting", description: "Are results measured and acted on?", items: [
    "Key metrics are defined (reach, engagement, clicks, leads)",
    "Native analytics or a reporting tool is checked regularly",
    "Reports are shared on a regular schedule",
    "Best and worst posts are reviewed to guide the plan",
    "Competitors are benchmarked",
    "Goals and targets are set and reviewed",
  ] },
  // ---- Platform sections
  { key: "instagram", group: "platform", platform: "instagram", title: "Instagram", description: "Platform specific checks for Instagram.", items: [
    "Reels are posted regularly and use trending audio well",
    "Stories are used several times a week with stickers and links",
    "Story Highlights are organised with designed covers",
    "Grid looks cohesive when a visitor opens the profile",
    "Carousels are used for education and saves",
    "Alt text is added to posts",
    "Collab posts, tags and location tags are used",
    "Shopping or product tags are enabled where relevant",
    "Broadcast channel or close friends are used to build loyalty",
  ] },
  { key: "facebook", group: "platform", platform: "facebook", title: "Facebook", description: "Platform specific checks for Facebook.", items: [
    "Page About section is complete (hours, address, services, links)",
    "Call to action button is set and works",
    "Cover video or image is current",
    "Messenger auto replies and saved replies are set up",
    "Reviews and recommendations are answered",
    "Facebook Groups or events are used for community",
    "Reels and video are used, not only link posts",
    "Page roles and access are managed securely",
    "Meta Business Suite is connected for scheduling and insights",
  ] },
  { key: "linkedin", group: "platform", platform: "linkedin", title: "LinkedIn", description: "Platform specific checks for LinkedIn.", items: [
    "Company page is complete with tagline, about, specialties and logo",
    "Page posts at least weekly with a mix of formats",
    "Employees are linked to the page and share its content",
    "Founders and leaders have optimised personal profiles",
    "Document posts, polls or video are used",
    "Newsletter or events are used where relevant",
    "Featured section highlights key offers or case studies",
    "Comments are answered and the page engages with others",
    "Careers or hiring content supports the employer brand",
  ] },
  { key: "youtube", group: "platform", platform: "youtube", title: "YouTube", description: "Platform specific checks for YouTube.", items: [
    "Channel banner, icon and description are on brand",
    "Channel trailer or featured video is set",
    "Video titles are keyword aware and compelling",
    "Descriptions have keywords, links and timestamps",
    "Custom thumbnails are used and consistent",
    "Playlists organise the content",
    "Shorts are used alongside long videos",
    "End screens and cards guide viewers to the next step",
    "Captions are uploaded and comments are answered",
  ] },
  { key: "x", group: "platform", platform: "x", title: "X (Twitter)", description: "Platform specific checks for X.", items: [
    "Profile, header and pinned post are current",
    "Posting cadence is regular with a mix of text, media and threads",
    "Replies and mentions are answered quickly",
    "Lists or communities are used to follow and engage",
    "Threads are used to share depth",
    "Hashtags are used sparingly and relevantly",
  ] },
  { key: "tiktok", group: "platform", platform: "tiktok", title: "TikTok", description: "Platform specific checks for TikTok.", items: [
    "Bio and link are complete",
    "Videos hook in the first second and use on-screen text",
    "Trends and sounds are used in a way that fits the brand",
    "Posting is frequent enough to feed the algorithm",
    "Comments are answered, including with video replies",
    "Series or playlists are used",
    "Captions include keywords for TikTok search",
  ] },
  { key: "pinterest", group: "platform", platform: "pinterest", title: "Pinterest", description: "Platform specific checks for Pinterest.", items: [
    "Business account is claimed and the website is verified",
    "Boards are organised with keyword-rich titles and descriptions",
    "Pins use vertical images with clear text overlays",
    "Pins link to relevant landing pages",
    "Rich pins are enabled",
    "New pins are added regularly",
  ] },
];

export const GENERAL_SECTIONS = LIBRARY.filter((s) => s.group === "general");
export const PLATFORM_SECTIONS = LIBRARY.filter((s) => s.group === "platform");
export const getLibrarySection = (key: string) => LIBRARY.find((s) => s.key === key) ?? null;
